# Generated by Django 3.0.3 on 2020-02-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0003_auto_20200215_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Михаил', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='+380957250222', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(default='Яценко', max_length=50),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
