# Generated by Django 3.0.3 on 2020-02-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0004_auto_20200216_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(default='Toyta', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(default=123, max_length=50),
        ),
    ]
