# Generated by Django 3.0.3 on 2020-02-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0005_auto_20200216_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
    ]
