# Generated by Django 3.0.3 on 2020-02-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0006_remove_order_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taxiapp.Car'),
        ),
    ]
