# Generated by Django 3.0.3 on 2020-02-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiapp', '0007_order_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
